baseURL = 'https://aokomorowski.github.io/'
languageCode = 'en-us'
title = 'Artur Komorowski blog'
theme = 'ananke'
[params]
  [params.contact]
    github = '@aokomorowski'
  [[params.ananke_socials]]
    name = "github"
    url = "https://github.com/aokomorowski"
    label = "GitHub Account"
    color = "#ff6800"
[services]
  [services.googleAnalytics]
    ID = "G-5NSX9EH5C9"
